name: CopperAX
version: 0.0.6-SNAPSHOT
main: it.shulkered.CopperAX.CopperAX
description: "The freshest free anti exploit out there."
authors: [DottoXD]
api-version: 1.21.11
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
