name: Build CopperAX

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/**.jar
